source 'https://cdn.cocoapods.org/'
platform :ios, '9.0'

target 'RhinoAppTest' do
  pod 'Rhino-iOS', '~> 2.1.3'
end

target 'RhinoAppTestUITests' do
  pod 'Rhino-iOS', '~> 2.1.3'
end

target 'PerformanceTest' do
  pod 'Rhino-iOS', '~> 2.1.3'
end
