source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'

target 'RhinoAppTest' do
  pod 'Rhino-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/rhino/v2.2/binding/ios/Rhino-iOS.podspec'
end

target 'RhinoAppTestUITests' do
  pod 'Rhino-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/rhino/v2.2/binding/ios/Rhino-iOS.podspec'
end

target 'PerformanceTest' do
  pod 'Rhino-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/rhino/v2.2/binding/ios/Rhino-iOS.podspec'
end
