name: Run filedemo

inputs:
  access_key:
    required: true
  library_path:
    required: true
  model_path:
    required: true
  context_path:
    required: true
  sensitivity:
    default: 0.5
  require_endpoint:
    default: "true"
  audio_path:
    required: true

runs:
  using: "composite"
  steps:
  - run: >
      ./build/rhino_demo_file
      -a ${{ inputs.access_key }}
      -l ${{ inputs.library_path }}
      -m ${{ inputs.model_path }}
      -c ${{ inputs.context_path }}
      -t ${{ inputs.sensitivity }}
      -e ${{ inputs.require_endpoint }}
      -w ${{ inputs.audio_path }}
    working-directory: demo/c
    shell: bash
