source 'https://cdn.cocoapods.org/'
platform :ios, '11.0'

target 'RhinoDemo' do
    pod 'Rhino-iOS', :podspec => 'https://raw.githubusercontent.com/Picovoice/rhino/v3.0-ios/binding/ios/Rhino-iOS.podspec'
end
