name: Android Performance

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'lib/android/**'
      - 'lib/common/**'
      - 'resources/contexts/android/**'
      - '.github/workflows/android-perf.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'lib/android/**'
      - 'lib/common/**'
      - 'resources/contexts/android/**'
      - '.github/workflows/android-perf.yml'

defaults:
  run:
    working-directory: demo/android/Activity

jobs:
  build:
    name: Run Android Speed Tests on AppCenter
    runs-on: ubuntu-latest

    strategy:
      matrix:
        device: [single-android, 32bit-android]
        include:
        - device: single-android
          performanceThresholdSec: 0.2
        - device: 32bit-android
          performanceThresholdSec: 0.4

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v2.4.0

    - name: Install AppCenter CLI
      run: npm install -g appcenter-cli

    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Copy test_resources
      run: ./copy_test_resources.sh

    - name: Inject AccessKey
      run: echo pvTestingAccessKey="${{secrets.PV_VALID_ACCESS_KEY}}" >> local.properties

    - name: Inject Number of Iterations
      run: echo numTestIterations="100" >> local.properties

    - name: Inject Performance Threshold
      run: echo performanceThresholdSec="${{ matrix.performanceThresholdSec }}" >> local.properties

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build app
      run: ./gradlew assembleDebug

    - name: Build androidTest
      run: ./gradlew assembleAndroidTest

    - name: Run tests on AppCenter
      run: appcenter test run espresso
        --token ${{secrets.APPCENTERAPITOKEN}}
        --app "Picovoice/Rhino-Android-Activity"
        --devices "Picovoice/${{ matrix.device }}"
        --app-path rhino-activity-demo-app/build/outputs/apk/debug/rhino-activity-demo-app-debug.apk
        --test-series "rhino-android"
        --locale "en_US"
        --build-dir rhino-activity-demo-app/build/outputs/apk/androidTest/debug
