name: Angular

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'binding/angular/**'
      - '!binding/angular/README.md'
      - 'lib/wasm/**'
      - 'resources/contexts/wasm/**'
      - '.github/workflows/angular.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'binding/angular/**'
      - '!binding/angular/README.md'
      - 'lib/wasm/**'
      - 'resources/contexts/wasm/**'
      - '.github/workflows/angular.yml'

defaults:
  run:
    working-directory: binding/angular

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 20.x]

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Pre-build dependencies
      run: npm install yarn

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build rhino-angular

    - name: Lint
      run: yarn lint

    - name: Setup test
      run: yarn setup-test

    - name: Run test
      run: yarn test --env ACCESS_KEY=${{secrets.PV_VALID_ACCESS_KEY}}
