name: Angular

on:
  workflow_dispatch:
  push:
    branches: [ master, v2.0 ]
    paths:
      - 'binding/angular/**'
      - '!binding/angular/README.md'
      - 'lib/wasm/**'
      - 'resources/contexts/wasm/**'
  pull_request:
    branches: [ master, v2.0 ]
    paths:
      - 'binding/angular/**'
      - '!binding/angular/README.md'
      - 'lib/wasm/**'
      - 'resources/contexts/wasm/**'

defaults:
  run:
    working-directory: binding/angular

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Pre-build dependencies
      run: npm install yarn

    - name: Local package dependencies
      run: |
        yarn
        yarn build
        for i in rhino-web*; do cd $i; yarn && yarn build || exit 1; cd ..; done
      working-directory: binding/web

    - name: Install dependencies
      run: yarn install

    - name: Build
      run: yarn build rhino-web-angular --prod

    - name: Lint
      run: yarn lint
