name: C Demos

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'demo/c/**'
      - '!demo/c/README.md'
      - 'lib/beaglebone/**'
      - 'lib/common/**'
      - 'lib/linux/**'
      - 'lib/jetson/**'
      - 'lib/mac/**'
      - 'lib/raspberry-pi/**'
      - 'lib/windows/**'
      - 'resources/contexts/beaglebone/**'
      - 'resources/contexts/jetson/**'
      - 'resources/contexts/linux/**'
      - 'resources/contexts/mac/**'
      - 'resources/contexts/raspberry-pi/**'
      - 'resources/contexts/windows/**'
      - '.github/workflows/c-demos.yml'
  pull_request:
    branches: [ master ]
    paths:
      - 'demo/c/**'
      - '!demo/c/README.md'
      - 'lib/beaglebone/**'
      - 'lib/common/**'
      - 'lib/linux/**'
      - 'lib/jetson/**'
      - 'lib/mac/**'
      - 'lib/raspberry-pi/**'
      - 'lib/windows/**'
      - 'resources/contexts/beaglebone/**'
      - 'resources/contexts/jetson/**'
      - 'resources/contexts/linux/**'
      - 'resources/contexts/mac/**'
      - 'resources/contexts/raspberry-pi/**'
      - 'resources/contexts/windows/**'
      - '.github/workflows/c-demos.yml'

defaults:
  run:
    working-directory: demo/c

jobs:
  build-micdemo-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create build directory
      run: cmake -B ./build

    - name: Build micdemo
      run: cmake --build ./build --target rhino_demo_mic

  build-micdemo-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi2, rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson, beaglebone]

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create build directory
      run: cmake -B ./build

    - name: Build micdemo
      run: cmake --build ./build --target rhino_demo_mic

  build-filedemo-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        include:
        - os: ubuntu-latest
          platform: linux
          arch: x86_64
          ext: so
        - os: windows-latest
          platform: windows
          arch: amd64
          ext: dll
        - os: macos-latest
          platform: mac
          arch: x86_64
          ext: dylib

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create build directory
      run: cmake -B ./build

    - name: Build filedemo
      run: cmake --build ./build --target rhino_demo_file

    - uses: ./.github/actions/c-filedemo
      name: Run filedemo (en)
      with:
        access_key: ${{ secrets.PV_VALID_ACCESS_KEY }}
        library_path: ../../lib/${{ matrix.platform }}/${{ matrix.arch }}/libpv_rhino.${{ matrix.ext }}
        model_path: ../../lib/common/rhino_params.pv
        context_path: ../../resources/contexts/${{ matrix.platform }}/coffee_maker_${{ matrix.platform }}.rhn
        audio_path: ../../resources/audio_samples/test_within_context.wav

    - uses: ./.github/actions/c-filedemo
      name: Run filedemo (de)
      with:
        access_key: ${{ secrets.PV_VALID_ACCESS_KEY }}
        library_path: ../../lib/${{ matrix.platform }}/${{ matrix.arch }}/libpv_rhino.${{ matrix.ext }}
        model_path: ../../lib/common/rhino_params_de.pv
        context_path: ../../resources/contexts_de/${{ matrix.platform }}/beleuchtung_${{ matrix.platform }}.rhn
        audio_path: ../../resources/audio_samples/test_within_context_de.wav

    - uses: ./.github/actions/c-filedemo
      name: Run filedemo (es)
      with:
        access_key: ${{ secrets.PV_VALID_ACCESS_KEY }}
        library_path: ../../lib/${{ matrix.platform }}/${{ matrix.arch }}/libpv_rhino.${{ matrix.ext }}
        model_path: ../../lib/common/rhino_params_es.pv
        context_path: ../../resources/contexts_es/${{ matrix.platform }}/iluminación_inteligente_${{ matrix.platform }}.rhn
        audio_path: ../../resources/audio_samples/test_within_context_es.wav

    - uses: ./.github/actions/c-filedemo
      name: Run filedemo (fr)
      with:
        access_key: ${{ secrets.PV_VALID_ACCESS_KEY }}
        library_path: ../../lib/${{ matrix.platform }}/${{ matrix.arch }}/libpv_rhino.${{ matrix.ext }}
        model_path: ../../lib/common/rhino_params_fr.pv
        context_path: ../../resources/contexts_fr/${{ matrix.platform }}/éclairage_intelligent_${{ matrix.platform }}.rhn
        audio_path: ../../resources/audio_samples/test_within_context_fr.wav

  build-filedemo-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi2, rpi3-32, rpi3-64, rpi4-32, rpi4-64, jetson, beaglebone]
        include:
        - machine: rpi2
          platform: raspberry-pi
          arch: cortex-a7
        - machine: rpi3-32
          platform: raspberry-pi
          arch: cortex-a53
        - machine: rpi3-64
          platform: raspberry-pi
          arch: cortex-a53-aarch64
        - machine: rpi4-32
          platform: raspberry-pi
          arch: cortex-a72
        - machine: rpi4-64
          platform: raspberry-pi
          arch: cortex-a72-aarch64
        - machine: jetson
          platform: jetson
          arch: cortex-a57-aarch64
        - machine: beaglebone
          platform: beaglebone
          arch: ''

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Create build directory
      run: cmake -B ./build

    - name: Build filedemo
      run: cmake --build ./build --target rhino_demo_file

    - uses: ./.github/actions/c-filedemo
      name: Run filedemo (en)
      with:
        access_key: ${{ secrets.PV_VALID_ACCESS_KEY }}
        library_path: ../../lib/${{ matrix.platform }}/${{ matrix.arch }}/libpv_rhino.so
        model_path: ../../lib/common/rhino_params.pv
        context_path: ../../resources/contexts/${{ matrix.platform }}/coffee_maker_${{ matrix.platform }}.rhn
        audio_path: ../../resources/audio_samples/test_within_context.wav

    - uses: ./.github/actions/c-filedemo
      name: Run filedemo (de)
      with:
        access_key: ${{ secrets.PV_VALID_ACCESS_KEY }}
        library_path: ../../lib/${{ matrix.platform }}/${{ matrix.arch }}/libpv_rhino.so
        model_path: ../../lib/common/rhino_params_de.pv
        context_path: ../../resources/contexts_de/${{ matrix.platform }}/beleuchtung_${{ matrix.platform }}.rhn
        audio_path: ../../resources/audio_samples/test_within_context_de.wav

    - uses: ./.github/actions/c-filedemo
      name: Run filedemo (es)
      with:
        access_key: ${{ secrets.PV_VALID_ACCESS_KEY }}
        library_path: ../../lib/${{ matrix.platform }}/${{ matrix.arch }}/libpv_rhino.so
        model_path: ../../lib/common/rhino_params_es.pv
        context_path: ../../resources/contexts_es/${{ matrix.platform }}/iluminación_inteligente_${{ matrix.platform }}.rhn
        audio_path: ../../resources/audio_samples/test_within_context_es.wav

    - uses: ./.github/actions/c-filedemo
      name: Run filedemo (fr)
      with:
        access_key: ${{ secrets.PV_VALID_ACCESS_KEY }}
        library_path: ../../lib/${{ matrix.platform }}/${{ matrix.arch }}/libpv_rhino.so
        model_path: ../../lib/common/rhino_params_fr.pv
        context_path: ../../resources/contexts_fr/${{ matrix.platform }}/éclairage_intelligent_${{ matrix.platform }}.rhn
        audio_path: ../../resources/audio_samples/test_within_context_fr.wav
