name: Go Demos

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'demo/go/**'
      - '!demo/go/README.md'
      - '.github/workflows/go-demos.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/go/**'
      - '!demo/go/README.md'
      - '.github/workflows/go-demos.yml'


defaults:
  run:
    working-directory: demo/go

jobs:
  build-github-hosted:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        go: [ '1.16', '1.17', '1.18', '1.19', '1.20', 'stable' ]
        include:
        - os: ubuntu-latest
          platform: linux
        - os: windows-latest
          platform: windows
        - os: macos-latest
          platform: mac

    steps:
    - uses: actions/checkout@v3

    - name: Set up Mingw
      uses: egor-tensin/setup-mingw@v2
      if: ${{ (matrix.os == 'windows-latest') && (matrix.go != 'stable') && (matrix.go < 1.20) }}
      with:
        version: 11.2.0

    - name: Set up go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}

    - name: Build micdemo
      run: go build micdemo/rhino_mic_demo.go

    - name: Build filedemo
      run: go build filedemo/rhino_file_demo.go

    - name: Test filedemo
      run: ./rhino_file_demo -access_key ${{secrets.PV_VALID_ACCESS_KEY}} -input_audio_path ../../resources/audio_samples/test_within_context.wav -context_path ../../resources/contexts/${{ matrix.platform }}/coffee_maker_${{ matrix.platform }}.rhn

  build-self-hosted:
    runs-on: ${{ matrix.machine }}

    strategy:
      matrix:
        machine: [rpi3-32, rpi3-64, rpi4-32, rpi4-64, rpi5-64]
        include:
        - machine: rpi3-32
          platform: raspberry-pi
        - machine: rpi3-64
          platform: raspberry-pi
        - machine: rpi4-32
          platform: raspberry-pi
        - machine: rpi4-64
          platform: raspberry-pi
        - machine: rpi5-64
          platform: raspberry-pi

    steps:
    - uses: actions/checkout@v3

    - name: Build micdemo
      run: go build micdemo/rhino_mic_demo.go

    - name: Build filedemo
      run: go build filedemo/rhino_file_demo.go

    - name: Test filedemo
      run: ./rhino_file_demo -access_key ${{secrets.PV_VALID_ACCESS_KEY}} -input_audio_path ../../resources/audio_samples/test_within_context.wav -context_path ../../resources/contexts/${{ matrix.platform }}/coffee_maker_${{ matrix.platform }}.rhn

