name: iOS Demos

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'demo/ios/**'
      - '.github/workflows/ios-demos.yml'
  pull_request:
    branches: [ master, 'v[0-9]+.[0-9]+' ]
    paths:
      - 'demo/ios/**'
      - '.github/workflows/ios-demos.yml'

jobs:
  build:
    runs-on: macos-latest
    defaults:
      run:
        working-directory: demo/ios

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*

      - name: Install Cocoapods
        run: gem install cocoapods

      - name: Install AppCenter CLI
        run: npm install -g appcenter-cli

      - name: Make build dir
        run: mkdir ddp

      - name: Run Cocoapods
        run: pod install

      - name: Build English
        run: xcrun xcodebuild build
          -configuration Debug
          -workspace RhinoDemo.xcworkspace
          -sdk iphoneos
          -scheme enDemo
          -derivedDataPath ddp
          CODE_SIGNING_ALLOWED=NO

      - name: Build Other Language
        run: xcrun xcodebuild build
          -configuration Debug
          -workspace RhinoDemo.xcworkspace
          -sdk iphoneos
          -scheme frDemo
          -derivedDataPath ddp
          CODE_SIGNING_ALLOWED=NO